"use server";

import { createServerSupabaseClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import { GoogleGenAI } from "@google/genai"; // Ensure you have this installed!

// Initialize the Gemini SDK
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function analyzeTextAction(
  content: string,
  title: string = "Untitled Scan",
) {
  const supabase = await createServerSupabaseClient();

  // 1. Get current user
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error("Unauthorized");

  // 2. Call Gemini to simulate/perform AI detection
  // Gemini is an LLM, so we prompt it to evaluate the text objectively.
  let aiScore = 50; // Default fallback fallback

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash", // Use a fast, capable model
      contents: `You are an advanced AI content detector. Analyze the following text and return ONLY a JSON object with a score between 0 and 100 representing the probability that this text was generated by an AI (100 means definitely AI, 0 means definitely human).
      
      Text to analyze: "${content}"`,
      config: {
        responseMimeType: "application/json", // Forces Gemini to return pure JSON
      },
    });

    const resultText = response.text;
    const data = JSON.parse(resultText || "{}");
    aiScore = data.score ?? 50;
  } catch (error) {
    console.error("Gemini Analysis Failed:", error);
    // You could decide to fail the request or just use a fallback score
  }

  // 3. Save the document first (ALIGNED WITH NEW SCHEMA)
  // Since we made 'humanized_content' and 'tone_used' NOT NULL, we must provide them!
  const { data: doc, error: docError } = await supabase
    .from("documents")
    .insert({
      user_id: user.id,
      title: title,
      original_content: content, // Corrected from 'content'
      humanized_content: content, // Since this is just a scan, we'll store the original as the output too
      tone_used: "analytical", // Default fallback
    })
    .select()
    .single();

  if (docError) throw new Error(docError.message);

  // 4. Save the result
  const { error: resultError } = await supabase
    .from("detection_results")
    .insert({
      document_id: doc.id,
      user_id: user.id,
      ai_score: aiScore / 100, // Storing as a decimal (e.g., 0.85 for 85%)
      details: {
        model: "Gemini-2.5-Detector",
        word_count: content.split(/\s+/).length,
      },
    });

  if (resultError) throw new Error(resultError.message);

  // 5. Update the UI cache
  revalidatePath("/dashboard");

  return { success: true, score: aiScore };
}
