import type { Metadata } from "next";
import { buildBreadcrumbJsonLd, buildMetadata } from "@/lib/seo";
import { StructuredData } from "@/components/seo/StructuredData";
import { siteConfig } from "@/lib/site";

export async function generateMetadata(): Promise<Metadata> {
  return buildMetadata({
    title: "Terms of Service",
    description: "Terms of Service for Text Humanica — read before using our AI detection and humanization platform.",
    path: "/terms",
    noIndex: false,
  });
}

export default function TermsPage() {
  const lastUpdated = "May 1, 2026";

  return (
    <>
      <StructuredData data={buildBreadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Terms of Service", path: "/terms" }])} />
      <div className="mx-auto max-w-3xl px-4 py-14">
        <header className="mb-10">
          <p className="text-sm font-bold uppercase tracking-[0.2em] text-indigo-600">Legal</p>
          <h1 className="mt-3 text-4xl font-extrabold tracking-tight text-slate-900">Terms of Service</h1>
          <p className="mt-3 text-sm text-slate-500">Last updated: {lastUpdated}</p>
        </header>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-700">

          <section>
            <h2 className="text-xl font-bold text-slate-900">1. Acceptance of Terms</h2>
            <p>By accessing or using {siteConfig.name} ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service. These terms apply to all users, including visitors, registered users, and paying subscribers.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">2. Description of Service</h2>
            <p>{siteConfig.name} provides AI-powered text detection and humanization tools. The Service analyzes text to estimate the probability that it was generated by an AI model, and rewrites text to reduce AI-detectable patterns. The Service is intended for legitimate writing assistance, research, and educational purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">3. Acceptable Use</h2>
            <p>You agree to use the Service only for lawful purposes. You must not:</p>
            <ul className="mt-3 list-disc space-y-1 pl-6">
              <li>Submit text that violates any applicable law or regulation</li>
              <li>Use the Service to facilitate academic fraud, plagiarism, or misrepresentation in contexts where such conduct is prohibited</li>
              <li>Attempt to reverse-engineer, scrape, or extract the underlying AI models or algorithms</li>
              <li>Use automated scripts or bots to access the Service beyond the documented API</li>
              <li>Share your account credentials with others or allow unauthorized access to your account</li>
              <li>Submit content that is defamatory, obscene, or infringes on third-party intellectual property rights</li>
            </ul>
            <p className="mt-3">You are solely responsible for the content you submit and for how you use the output of the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">4. Accounts and Registration</h2>
            <p>To access most features, you must create an account. You agree to provide accurate, current, and complete information during registration and to keep your account information updated. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account.</p>
            <p className="mt-3">We reserve the right to suspend or terminate accounts that violate these Terms or that we reasonably believe are being used fraudulently.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">5. Subscriptions and Billing</h2>
            <p>Paid plans are billed through Polar, our payment processor. By subscribing, you authorize recurring charges at the rate and cadence you selected. All prices are in USD and exclusive of applicable taxes.</p>
            <p className="mt-3">You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. We do not issue refunds for partial billing periods or unused word quotas.</p>
            <p className="mt-3">We reserve the right to change pricing with 30 days' notice. Continued use of the Service after a price change constitutes acceptance of the new pricing.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">6. Word Quotas and Usage Limits</h2>
            <p>Each plan includes a word quota that resets monthly (or weekly for the Pro Weekly plan). Unused words do not roll over. If you exceed your quota, you will receive an error and must upgrade your plan or wait for the next reset period.</p>
            <p className="mt-3">We reserve the right to enforce rate limits to ensure fair access for all users.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">7. Intellectual Property</h2>
            <p>You retain ownership of all text you submit to the Service. By submitting text, you grant us a limited, non-exclusive license to process it solely for the purpose of providing the Service to you.</p>
            <p className="mt-3">The Service, including its software, design, and underlying AI models, is owned by {siteConfig.name} and protected by intellectual property laws. You may not copy, modify, or distribute any part of the Service without our written permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">8. Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that detection or humanization results will be accurate or suitable for any particular purpose.</p>
            <p className="mt-3">AI detection and humanization are probabilistic processes. Results may vary and should not be relied upon as definitive assessments. Always review output before use.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, {siteConfig.name} shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to academic penalties, professional consequences, or data loss.</p>
            <p className="mt-3">Our total liability to you for any claim arising from these Terms or your use of the Service shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">10. Changes to Terms</h2>
            <p>We may update these Terms at any time. We will notify you of material changes by email or by posting a notice on the Service. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900">11. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="/contact" className="text-indigo-600 hover:underline">our contact page</a>.</p>
          </section>

        </div>
      </div>
    </>
  );
}
